Blast\Bundle\BaseEntitiesBundle\Entity\SearchIndexEntity:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        field:
            type: string
            length: 255
        keyword:
            type: string
            length: 255
