services:
    blast_base_entities.admin.search_index_entity:
        class: Blast\BaseEntitiesBundle\Admin\SearchIndexEntityAdmin
        arguments: [~, Blast\BaseEntitiesBundle\Entity\SearchIndexEntity, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: SearchIndexEntity
        calls: 
            - [ setTemplate, [ edit, BlastCoreBundle:CRUD:base_edit.html.twig ] ]
            - [ setTemplate, [ list, BlastCoreBundle:CRUD:base_list.html.twig ] ]
            - [ setTemplate, [ show, BlastCoreBundle:CRUD:base_show.html.twig ] ]
            
