parameters:
    blast:
        configuration:
            templates:
                list:
                    sort_rank: LibrinfoBaseEntitiesBundle:CRUD:list_field_sort_rank.html.twig

        Librinfo\BaseEntitiesBundle\Entity\Traits\Addressable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    zip: ~
                    city: ~
                    country: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    zip: ~
                    city: ~
                    country: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        form_group_main_address:
                            address:
                                type: textarea
                                required: false
                            zip: ~
                            city: ~
                            country: ~
                            npai: ~
                    form_group_specifics:
                        form_group_communication:
                            vcard_uid:
                                type: text
                                read_only: true
                                disabled: true
                                required: false



        Librinfo\BaseEntitiesBundle\Entity\Traits\Emailable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    email:
                        type: email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    email: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            email:
                                type: email
                                required: false
                    form_group_specifics:
                        form_group_email:
                            emailNpai: ~
                            emailNoNewsletter: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Nameable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name: ~

        Librinfo\BaseEntitiesBundle\Entity\Traits\Descriptible:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        form_group_description:
                            description: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        form_group_description:
                            description:
                                type: textarea
                                required: false

        Librinfo\BaseEntitiesBundle\Entity\Traits\Labelable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            label: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    createdAt: ~
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_tab_history:
                        form_group_history:
                            createdAt: ~
                            updatedAt: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_history:
                        form_group_history:
                            createdAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true
                            updatedAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true


        Librinfo\BaseEntitiesBundle\Entity\Traits\Guidable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [id]
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [id]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                remove: [id]

        Librinfo\BaseEntitiesBundle\Entity\Traits\Treeable:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            parentNode:
                                type: librinfo_baseentities_treeable


        Librinfo\BaseEntitiesBundle\Entity\Traits\Sortable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    sortRank:
                        type: sort_rank
                    _extra_templates: [LibrinfoBaseEntitiesBundle:CRUD:list_extra_sortable.html.twig]
        
       ### DOCTRINE ### 
        
        Librinfo\BaseEntitiesBundle\Entity\Traits\Emailable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    email:
                        type: email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    email: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            email:
                                type: email
                                required: false
                            emailNpai: ~
                            emailNoNewsletter: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Nameable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name:
                        identifier: true
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name: ~

        Librinfo\BaseEntitiesBundle\Entity\Traits\Descriptible:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        Description:
                            description:
                                type: textarea
                                label: ''

        Librinfo\BaseEntitiesBundle\Entity\Traits\Labelable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            label: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    createdAt: ~
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_specifics:
                        form_group_misc:
                            createdAt: ~
                            updatedAt: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_specifics:
                        form_group_misc:
                            createdAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true
                            updatedAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true


        Librinfo\BaseEntitiesBundle\Entity\Traits\Guidable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [id]
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [id]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                remove: [id]

        Librinfo\BaseEntitiesBundle\Entity\Traits\Treeable:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            parentNode:
                                type: librinfo_baseentities_treeable