# TODO: this is not loaded (temporarily moved to app/config/config.yml)
# TODO: find why it is not loaded from LibrinfoBaseEntitiesExtension

parameters:
    doctrine.orm.metadata.yml.class: Librinfo\BaseEntitiesBundle\Doctrine\ORM\Driver\SearchableYamlDriver

librinfo_base_entities:
    doctrine:
        orm:
            class_metadata_factory_name:  Doctrine\ORM\Mapping\ClassMetadataFactory