parameters:
    librinfo:
        Librinfo\BaseEntitiesBundle\Entity\Traits\Addressable:
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
                    email: ~
                    zip: ~
                    city: ~
                    country: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        Address:
                            address:
                                type: textarea
                                required: false
                            zip: ~
                            city: ~
                            country: ~
                    Specifics:
                        Communication:
                            description: ~
                            vcard_uid:
                                type: text
                                read_only: true
                                disabled: true
                                required: false
                        Address:
                            npai: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Emailable:
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    email: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            email: ~
                    Specifics:
                        Email:
                            emailNpai: ~
                            emailNoNewsletter: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Nameable:
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name: ~


        Librinfo\BaseEntitiesBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Specifics:
                        Misc:
                            createdAt:
                                type: text
                                read_only: true
                                disabled: true
                                required: false
                            updatedAt:
                                type: text
                                read_only: true
                                disabled: true
                                required: false


        Librinfo\BaseEntitiesBundle\Entity\Traits\BaseEntity:
            Sonata\AdminBundle\Form\FormMapper:
                remove: [id]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                remove: [id]
