parameters:
    librinfo:
        configuration:
            templates:
                list:
                    sort_rank: LibrinfoBaseEntitiesBundle:CRUD:list_field_sort_rank.html.twig

        Librinfo\DoctrineBundle\Entity\Traits\Addressable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    zip: ~
                    city: ~
                    country: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    zip: ~
                    city: ~
                    country: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        Address:
                            address:
                                type: textarea
                                required: false
                            zip: ~
                            city: ~
                            country: ~
                    Specifics:
                        Communication:
                            vcard_uid:
                                type: text
                                read_only: true
                                disabled: true
                                required: false
                        Address:
                            npai: ~


        Librinfo\DoctrineBundle\Entity\Traits\Emailable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    email:
                        type: email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    email: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            email:
                                type: email
                                required: false
                    Specifics:
                        Email:
                            emailNpai: ~
                            emailNoNewsletter: ~


        Librinfo\DoctrineBundle\Entity\Traits\Nameable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name: ~

        Librinfo\DoctrineBundle\Entity\Traits\Descriptible:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        Description:
                            description:
                                type: textarea
                                label: ' '

        Librinfo\DoctrineBundle\Entity\Traits\Labelable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    label: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            label: ~


        Librinfo\DoctrineBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    createdAt: ~
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    Specifics:
                        Misc:
                            createdAt: ~
                            updatedAt: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Specifics:
                        Misc:
                            createdAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true
                            updatedAt:
                                type: sonata_type_datetime_picker
                                read_only: true
                                disabled: true
                                required: false
                                dp_side_by_side: true


        Librinfo\DoctrineBundle\Entity\Traits\Guidable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [id]
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [id]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                remove: [id]

        Librinfo\DoctrineBundle\Entity\Traits\Treeable:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            parentNode:
                                type: librinfo_baseentities_treeable


        Librinfo\DoctrineBundle\Entity\Traits\Sortable:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    sortRank:
                        type: sort_rank
                    _extra_templates: [LibrinfoBaseEntitiesBundle:CRUD:list_extra_sortable.html.twig]
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    General:
                        '':
                            sortRank: ~
