services:

# ###################################################################################
#
#                             DOCTRINE BEHAVIORS
#
# doctrine.event_subscriber tags are added in LibrinfoBaseEntitiesExtension.php
# ###################################################################################

# Service that manages Table naming convention
    librinfo.base_entities.listener.naming:
        class: Librinfo\BaseEntitiesBundle\EventListener\NamingListener

# Service that manages GUID doctrine mapping
    librinfo.base_entities.listener.guidable:
        class: Librinfo\BaseEntitiesBundle\EventListener\GuidableListener
        calls:
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Traceable doctrine mapping and behavior
    librinfo.base_entities.listener.traceable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TraceableListener
        calls:
            - [setLogger, [@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%librinfo.user_bundle.user.class%]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Addressable doctrine mapping
    librinfo.base_entities.listener.addressable:
        class: Librinfo\BaseEntitiesBundle\EventListener\AddressableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Treeable doctrine mapping
    librinfo.base_entities.listener.treeable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TreeableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Nameable doctrine mapping
    librinfo.base_entities.listener.nameable:
        class: Librinfo\BaseEntitiesBundle\EventListener\NameableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Labelable doctrine mapping
    librinfo.base_entities.listener.labelable:
        class: Librinfo\BaseEntitiesBundle\EventListener\LabelableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Emailable doctrine mapping
    librinfo.base_entities.listener.emailable:
        class: Librinfo\BaseEntitiesBundle\EventListener\EmailableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Descriptible doctrine mapping
    librinfo.base_entities.listener.descriptible:
        class: Librinfo\BaseEntitiesBundle\EventListener\DescriptibleListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Searchable doctrine mapping
    librinfo.base_entities.listener.searchable:
        class: Librinfo\BaseEntitiesBundle\EventListener\SearchableListener
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# ###################################################################################
#
#                          SYMFONY CUSTOM FORM TYPES
#
# ###################################################################################

    librinfo_base_entities.form.type.librinfo_baseentities_treeable:
        class: Librinfo\BaseEntitiesBundle\Form\Type\TreeableType
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: form.type, alias: librinfo_baseentities_treeable }
    librinfo_base_entities.form.type.librinfo_baseentities_treeablechoice:
        class: Librinfo\BaseEntitiesBundle\Form\Type\TreeableChoiceType
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: form.type, alias: librinfo_baseentities_treeablechoice }

# ###################################################################################
#
#                          SEARCH ANALYZER
#
# ###################################################################################

    librinfo.base_entities.search_analyser:
        class: Librinfo\BaseEntitiesBundle\SearchAnalyser\SearchAnalyser