services:
    librinfo.base_entities.listener.mapping:
        class: Librinfo\BaseEntitiesBundle\EventListener\MappingListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    librinfo.base_entities.listener.traceable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%fos_user.model.user.class%]]

    librinfo.base_entities.listener.addressable:
        class: Librinfo\BaseEntitiesBundle\EventListener\AddressableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]