services:

# Service that manage Entity / Table naming convention

    librinfo.base_entities.listener.mapping:
        class: Librinfo\BaseEntitiesBundle\EventListener\MappingListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        calls:
            - [setClassAnalyser, [%knp.doctrine_behaviors.reflection.class_analyzer.class%]]

# Service that manage Traceable doctrine mapping and behavior

    librinfo.base_entities.listener.traceable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%librinfo.user_bundle.user.class%]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manage Addressable doctrine mapping

    librinfo.base_entities.listener.addressable:
        class: Librinfo\BaseEntitiesBundle\EventListener\AddressableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]
            - [setClassAnalyser, [%knp.doctrine_behaviors.reflection.class_analyzer.class%]]

# Service that manage Addressable doctrine mapping

    librinfo.base_entities.listener.treeable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TreeableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]
