services:
    librinfo.base_entities.listener.mapping:
        class: Librinfo\BaseEntitiesBundle\EventListener\MappingListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    librinfo.base_entities.listener.traceable:
        class: Librinfo\BaseEntitiesBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
#    librinfo.base_entities.tree.listener:
#        class: Librinfo\BaseEntitiesBundle\EventListener\TreeableListener
#        tags:
#            - { name: doctrine.event_listener, event: loadClassMetadata }
#    gedmo.listener.tree:
#        class: Gedmo\Tree\TreeListener
#        tags:
#          - { name: doctrine.event_subscriber, connection: default }
#        calls:
#          - [ setAnnotationReader, [ @annotation_reader ] ]