blast_base_entities:
    orm:
        default:
            naming:          true
            guidable:        true
            timestampable:   true
            addressable:     true
            treeable:        false
            nested_treeable: true
            nameable:        true
            labelable:       true
            emailable:       true
            descriptible:    true
            loggable:        true
            sortable:        true
            normalize:       true
            syliusGuidable:  true

    entity_searchable_indexes: ~

stof_doctrine_extensions:
    orm:
        default:
            tree:          true
            sluggable:     true
            timestampable: true
